### ISSUE TITLE
./data/poj104/token_vocab_dict.pkl does not exists

### ISSUE THREAD

**Issue by GuoXinrong** [jingkai92/learning-program-representation#1]
hello, I can't find the data folder among your project, I can only find the dataset folder, so I think you may not have uploaded the folder?
The complete error reporting information is as follows:
`[Util] ./data/poj104/token_vocab_dict.pkl does not exists. Please ensure file does exist.`

**Comment by jingkai92** [comment]
Hi @GuoXinrong,

Sorry for the mistake. I uploaded the dataset to Google Drive. Within the uploaded zip file, there are `.pkl` files that can fix the particular error you mentioned.

Thank you.

**Comment by GuoXinrong** [comment]
Hi @jingkai92 
I found some compression pack with the gzip suffix under the data folder,But I can't unzip the ".gzip" package(I use the gunzip *.gzip command and unzip '*.gzip' command ,they both don't work),maybe the suffix is  ".gz" or ".zip" ?

**Comment by jingkai92** [comment]
Hi @GuoXinrong,

I used `gzip` in the function ` def _load_data_from_json(self, js_path, gzip_format=True):` to load/save it. I am not sure if you can unzip it using gunzip. 

Thank you

**Comment by GuoXinrong** [comment]
Thanks for your timely reply,I run the command "python3 train.py --config_path ./ymls/clone_detection/tfidf/naivebayes.yml" directly, and it can  unzip the data documents automatically.
