### ISSUE TITLE
No module named 'evaluation.meteor'

### ISSUE THREAD

**Issue by GuoXinrong** [jingkai92/learning-program-representation#2]
I can't find the meteor folder under the evaluation folder either......
The complete error reporting information is as follows:
`File "/data/xinrongguo/learning-program-representation/evaluation/eval.py", line 13, in <module>
    from evaluation.meteor.meteor import Meteor
ModuleNotFoundError: No module named 'evaluation.meteor'`

**Comment by jingkai92** [comment]
Hi @GuoXinrong,

I updated the evaluation folder with the evaluation module. Please let me know if the error persists. 

Thank you.
